myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlinecourse/', include('onlinecourse.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'onlinecourse'
urlpatterns = [
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    path('<int:course_id>/enroll/', views.enroll, name='enroll'),
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path(
        '<int:course_id>/submission/<int:submission_id>/result/',
        views.show_exam_result,
        name='show_exam_result'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now


# Instructor model
class Instructor(models.Model):
    """ instructor model """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    """ learner model """
    STUDENT = 'STUDENT'
    DEVELOPER = 'DEVELOPER'
    DATA_SCIENTIST = 'DATA_SCIENTIST'
    DATABASE_ADMIN = 'DATABASE_ADMIN'

    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return f'{self.user.username}, {self.occupation}'


# Course model
class Course(models.Model):
    """ course model """
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)

    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Enrollment'
    )

    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return f"Name: {self.name}, Description: {self.description}"


# Lesson model
class Lesson(models.Model):
    """ lesson model """
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
class Enrollment(models.Model):
    """ enrollment model """
    AUDIT = 'AUDIT'
    HONOR = 'HONOR'
    BETA = 'BETA'

    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)


# Question model
class Question(models.Model):
    """ question model """
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    text = models.CharField(max_length=150)
    grade = models.FloatField()

    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(
            is_correct=True,
            id__in=selected_ids
        ).count()

        return all_answers == selected_correct


# Choice model
class Choice(models.Model):
    """ choice model """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=150)
    is_correct = models.BooleanField()


# Submission model
class Submission(models.Model):
    """ submission model """
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)

onlinecourse/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic

from .models import Course, Enrollment, Submission
from . import utils


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(
            request,
            'onlinecourse/user_registration_bootstrap.html',
            context
        )

    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        existing_user = User.objects.filter(username=username).first()

        if not existing_user:
            user = User.objects.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                password=password
            )

            login(request, user)
            return redirect("onlinecourse:index")

        context['message'] = "User already exists."
        return render(
            request,
            'onlinecourse/user_registration_bootstrap.html',
            context
        )


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('onlinecourse:index')

        context['message'] = "Invalid username or password."
        return render(
            request,
            'onlinecourse/user_login_bootstrap.html',
            context
        )

    return render(
        request,
        'onlinecourse/user_login_bootstrap.html',
        context
    )


def logout_request(request):
    logout(request)
    return redirect('onlinecourse:index')


class CourseListView(generic.ListView):
    template_name = 'onlinecourse/course_list_bootstrap.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = utils.check_if_enrolled(user, course)
        return courses


class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'onlinecourse/course_detail_bootstrap.html'


def enroll(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = utils.check_if_enrolled(user, course)
    if user.is_authenticated:
        if not is_enrolled:
            # Create an enrollment
            Enrollment.objects.create(user=user, course=course, mode='honor')
            course.total_enrollment += 1
            course.save()

        return HttpResponseRedirect(reverse(
            viewname='onlinecourse:course_details',
            args=(course.id,)
        ))

    return redirect('onlinecourse:login')


def submit(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = utils.check_if_enrolled(user, course)
    if user.is_authenticated:
        if is_enrolled:
            enrollment = Enrollment.objects.get(user=user, course=course)
            submission = Submission.objects.create(enrollment=enrollment)

            submitted_answers = [
                int(value)
                for key, value in request.POST.items()
                if key.startswith('choice')
            ]
            submission.choices.add(*submitted_answers)

            return HttpResponseRedirect(reverse(
                viewname='onlinecourse:show_exam_result',
                args=(course.id, submission.id,)
            ))

        return HttpResponseRedirect(reverse(
            viewname='onlinecourse:enroll',
            args=(course.id,)
        ))

    return redirect('onlinecourse:login')


def show_exam_result(request, course_id, submission_id):
    course = get_object_or_404(Course, pk=course_id)
    submission = get_object_or_404(Submission, pk=submission_id)
    choices = submission.choices.all()

    total_score, score = 0, 0
    for question in course.question_set.all():
        total_score += question.grade
        if question.is_get_score(choices):
            score += question.grade

    context = {
        "course": course,
        "choices": choices,
        "grade": int(score / total_score * 100),
    }

    return render(
        request,
        'onlinecourse/exam_result_bootstrap.html',
        context
    )

onlinecourse/templates/onlinecourse/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block customjs %}{% endblock %}
    <title>{% block title %}Online Courses{% endblock %}</title>
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- content block -->
    {% block content %}{% endblock %}

</body>

onlinecourse/templates/onlinecourse/course_detail_bootstrap.html
{% extends "onlinecourse/base.html" %}

{% block customjs %}
<!-- Custom JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
<!-- Page content -->
<div class="container-fluid">
    <h2>{{ course.name }}</h2>
    <div class="card-columns-vertical">
        {% for lesson in course.lesson_set.all %}
            <div class="card mt-1">
                <div class="card-header"><h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5></div>
                <div class="card-body">{{lesson.content}}</div>
            </div>
        {% endfor %}
    </div>

    <!-- show questions and choices -->
    <div class="card-columns-vertical">
        {% if user.is_authenticated %}
            <button class="btn btn-primary btn-block" data-toggle="collapse" data-target="#exam">Start Exam</button>
            <div id="exam" class="collapse">
                <form id="questionform" action="{% url 'onlinecourse:submit' course.id %}" method="post">
                    {% for question in course.question_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><h5>{{ question.text}}</h5></div>
                        {% csrf_token %}
                        <div class="form-group">
                            {% for choice in question.choice_set.all %}
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input type="checkbox" name="choice_{{choice.id}}"
                                        class="form-check-input" id="{{choice.id}}"
                                        value="{{choice.id}}">{{ choice.text }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <input class="btn btn-success btn-block" type="submit" value="Submit">
                </form>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

onlinecourse/templates/onlinecourse/course_list_bootstrap.html
{% extends "onlinecourse/base.html" %}

{% block content %}
<!-- Page content -->
{% if course_list %}
    <div class="container">
        <div class="card-deck">
            {% for course in course_list %}
                        <div class="card" style="width: 36rem;">
                        <img class="card-img-left" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                            alt="Course image">
                        <div class="card-body bg-light">
                            <h5 class="card-title">{{ course.name }}, <span class="text-success">
                                {{ course.total_enrollment}} enrolled</span></h5>
                        <p class="card-text">{{ course.description}}</p>
                        <form action="{% url 'onlinecourse:enroll' course.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-primary"  type="submit"
                                        value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} ">
                        </form>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <p>No courses are available.</p>
{% endif %}
{% endblock %}

onlinecourse/templates/onlinecourse/exam_result_bootstrap.html
{% extends "onlinecourse/base.html" %}

{% block content %}
<div class="container-fluid">
    {% if grade > 80 %}
        <div class="alert alert-success">
            <strong>Congratulation, {{ user.first_name }}!</strong> You have passed the exam and completed the course with score {{ grade }} / 100
        </div>
    {% else %}
        <div class="alert alert-danger">
            <strong>Failed</strong> Sorry, {{ user.first_name }}! You have failed the exam with score {{ grade }} / 100
        </div>
        <a class="btn btn-link text-danger" href="{% url 'onlinecourse:course_details' course.id %}">Re-test</a>
    {% endif %}
    
    <div class="card-columns-vertical mt-1">
        <h5 class="">Exam results</h5>
        {% for question in course.question_set.all %}
            <div class="card mt-1">
                <div class="card-header">
                    <h5>{{ question.text}}</h5>
                </div>
            
                {% csrf_token %}
                <div class="card-body">
                    {% for choice in question.choice_set.all %}
                        {% if choice in choices and choice.is_correct %}
                            <p class="text-success">Correct answer: {{ choice.text }}</p>
                        {% elif choice in choices and not choice.is_correct %}
                            <p class="text-danger">Incorrect answer: {{ choice.text }}</p>
                        {% elif not choice in choices and choice.is_correct %}
                            <p class="text-warning">Not selected: {{ choice.text }}</p>
                        {% else %}
                            <p class="text-dark">{{ choice.text }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

onlinecourse/templates/onlinecourse/user_login_bootstrap.html
{% extends "onlinecourse/base.html" %}

{% block content %}
<!-- Stylize Login form -->
<form action="{% url 'onlinecourse:login' %}" method="post">
    {% csrf_token %}
    <div class="container"> <!--Style root div with .container class -->
        <h1>Login</h1>
        <div class="form-group"> <!--Style second div with .form-group class -->
            <label for="username"><b>User Name</b></label>
            <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
            <label for="psw"><b>Password</b></label>
            <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
        </div>
        {% if message %}
            <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
            {{ message }}
            </div>
        {% endif %}
        <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
    </div>
</form>
{% endblock %}

onlinecourse/templates/onlinecourse/user_registration_bootstrap.html
{% extends "onlinecourse/base.html" %}

{% block content %}
<!-- Stylize Registration form -->
<form action="{% url 'onlinecourse:registration' %}" method="post">
    <div class="container">
        {% csrf_token %}
        <h1>Sign Up</h1>
        <hr>
        <div class="form-group">
            <label for="username"><b>User Name</b></label>
            <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required>
            <label for="firstname"><b>First Name</b></label>
            <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required>
            <label for="lastname"><b>Last Name</b></label>
            <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required>
            <label for="psw"><b>Password</b></label>
            <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required>
            {% if message %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Sign up</button>
        </div>
    </div>
</form>
{% endblock content %}